CREATE DATABASE SampleDB;
USE SampleDB;
CREATE TABLE Users (ID INT PRIMARY KEY IDENTITY(1,1), Name NVARCHAR(50), Email NVARCHAR(50));
CREATE TABLE Orders (OrderID INT PRIMARY KEY IDENTITY(1,1), UserID INT FOREIGN KEY REFERENCES Users(ID), OrderDate DATETIME DEFAULT GETDATE());